version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: notes-app-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: notes-app
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - notes-app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes-app-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/notes-app?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      BCRYPT_ROUNDS: 12
      PORT: 5000
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - notes-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes-app-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - notes-app-network

  # Test Environment
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: notes-app-test
    environment:
      NODE_ENV: test
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/notes-app-test?authSource=admin
      JWT_SECRET: test-secret-key
      BCRYPT_ROUNDS: 12
      VITE_API_URL: http://localhost:5000
    depends_on:
      mongodb:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - notes-app-network
    profiles:
      - test

volumes:
  mongodb_data:
    driver: local

networks:
  notes-app-network:
    driver: bridge
