name: Test Suite

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  docker-tests:
    name: Docker Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

            - name: Build and test with Docker Compose
        run: |
          # Build all services
          docker compose build
          
          # Start services and run tests
          docker compose --profile test up --abort-on-container-exit --exit-code-from test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            frontend/test-results/
            backend/coverage/
          retention-days: 30

      - name: Generate test summary
        if: always()
        run: |
          echo "## Docker Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Test Execution" >> $GITHUB_STEP_SUMMARY
          echo "- Backend tests: Completed" >> $GITHUB_STEP_SUMMARY
          echo "- Frontend tests: Completed" >> $GITHUB_STEP_SUMMARY
          echo "- Visual tests: Completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Coverage" >> $GITHUB_STEP_SUMMARY
          echo "- Backend coverage: Available in artifacts" >> $GITHUB_STEP_SUMMARY
          echo "- Test results: Available in artifacts" >> $GITHUB_STEP_SUMMARY

  # Optional: Build and push Docker images
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: docker-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/notes-app-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/notes-app-frontend:latest
